### ISSUE TITLE
when render small biezer line ,  the display is very weird 

### ISSUE THREAD

**Issue by emenwin** [audulus/vger#12]
I run the demo, and add some code in DemoView

`

        let bezPaint = vgerLinearGradient(vger, .init(x: 50, y: 450), .init(x: 100, y: 450), cyan, magenta, 0.0)
        // draw small biezer line 
        vgerStrokeBezier(vger, vgerBezierSegment(
            a: .init(x: 231, y: 81),
            b: .init(x: 233, y: 86),
            c: .init(x: 237 , y: 98  )), 4.0, bezPaint)
        
        vgerStrokeBezier(vger, vgerBezierSegment(a: .init(x: 50, y: 450), b: .init(x: 100, y: 450), c: .init(x: 100, y: 500)), 1.0, bezPaint)
        
        
        
        textAt(vger, 150, 450, "Quadratic Bezier stroke")
`

![Simulator Screen Shot - iPad Air (5th generation) - 2023-06-17 at 22 33 36](https://github.com/audulus/vger/assets/1106594/acf4ff99-86cb-4e23-8697-b937d8670854)

**Comment by wtholliday** [comment]
What happens if you replace `sdBezierApprox` with `sdBezier` here https://github.com/audulus/vger/blob/b499d9b9855d5b235149995c1bb364a0be468815/Sources/vger/sdf.h#L301

?

**Comment by emenwin** [comment]
It looks much better now.

```
case vgerBezier:
            // d = sdBezierApprox(p, prim.cvs[0], prim.cvs[1], prim.cvs[2]) - prim.width;
             d = sdBezier(p, prim.cvs[0], prim.cvs[1], prim.cvs[2]) - prim.width;
```
![Screenshot 2023-06-18 at 09 51 03](https://github.com/audulus/vger/assets/1106594/410f7542-4d3e-4ffe-9800-1d2b4191410a)

**Comment by emenwin** [comment]
It looks much better now.
```
case vgerBezier:
            // https://github.com/audulus/vger/issues/12
            // d = sdBezierApprox(p, prim.cvs[0], prim.cvs[1], prim.cvs[2]) - prim.width;
            d = sdBezier(p, prim.cvs[0], prim.cvs[1], prim.cvs[2]) - prim.width;
```
![Screenshot 2023-06-18 at 09 51 03](https://github.com/audulus/vger/assets/1106594/2343d94c-b1a1-4aaa-bffe-ea65b5b2acb2)
