### ISSUE TITLE
Missing antialiasing on some edges in VgerDemo...

### ISSUE THREAD

**Issue by luckyclan** [audulus/vger#4]
I noticed it in VgerDemo on iPad Pro 11 from 2018, and ipadOS 14.8
This also happens on very simple svg, like this:
`<path d='M10,10v50h50z' fill='#22ff22'/>`

![IMG_344AD2AF55DD-1](https://user-images.githubusercontent.com/31405913/153381193-75386636-7f38-44b6-8429-2518fd5d4af7.jpeg)

**Comment by luckyclan** [comment]
Here is a basic triangle (M10,10v50h50z) showing both antialiasing issue, and precision problem
![IMG_90FA58D57001-1](https://user-images.githubusercontent.com/31405913/153389328-c64e1df1-d971-4855-b2de-8d9232f53377.jpeg)
.

**Comment by wtholliday** [comment]
I turned off the SDF AA and bezier inside-outside test, leaving only the linear test, and that exhibits numerical issues:

<img width="537" alt="image" src="https://user-images.githubusercontent.com/841144/153455092-d33dd610-583c-4941-9f73-0f592e6863f4.png">

**Comment by luckyclan** [comment]
Rendering this triangle without aa will always display wrong pixels. Pixels on the edge are located exactly on the trinagle edge, so sometimes gpu rasterizer, due to rounding, will treat them as inside and sometimes outside the triangle.
However antialiasing should render perfect edges.

**Comment by wtholliday** [comment]
@luckyclan you're right, it's an AA issue. It seems that it's an issue with my SDF approximation (sdBezierApprox). If I set exact=true then I get good results:

<img width="461" alt="image" src="https://user-images.githubusercontent.com/841144/153488311-6941a7e7-db1b-4d25-be68-2b07273b7460.png">

**Comment by luckyclan** [comment]
Much better now. Does it affect the performance?

**Comment by luckyclan** [comment]
Did you try sdf bezier segment from this page / rendertoy: https://www.iquilezles.org/www/articles/distfunctions2d/distfunctions2d.htm

**Comment by luckyclan** [comment]
Yes, approx ver doesn’t look good.

I also wonder if you use naive or smart bounding box calculation for bezier: https://www.shadertoy.com/view/lsyfWc

I bet there is also optimization in sdf bezier so you would use sdf only for some selected pixels…

**Comment by wtholliday** [comment]
@luckyclan Yeah, I had some trivial rejection code in there already. It seems like using it with the exact bezier calculation doesn't result in too big of a performance regression. I can live with that :)

**Comment by luckyclan** [comment]
Could you try to work directly on cubic curve (without splitting it to two quadratic), using method from this:
https://www.shadertoy.com/view/4sKyzW

**Comment by luckyclan** [comment]
Btw, check my methods of converting cubic to quadratic:
https://www.shadertoy.com/view/7dlfRN

**Comment by dumblob** [comment]
> Yep. Tiger goes from .66ms in the fragment shader to 1.2ms on my machine.
>...
> @luckyclan Yeah, I had some trivial rejection code in there already. It seems like using it with the exact bezier calculation doesn't result in too big of a performance regression. I can live with that :)

Now that you made it the default I wonder how much is "not too big"? Is it around .66ms or rather 1.2ms?

**Comment by wtholliday** [comment]
@dumblob it made the fragment shader 2x slower. .66ms to 1.2ms.
